RADIUS_CLAMP = 8
INDENT = 15
WIDTH_WIRES = 2

COLOR_TEXT = '#121717'
COLOR_BG_INFO_FRAME = '#789897'
COLOR_BG_WORKSPACE = '#dcddd8'
COLOR_FRAME_OUTLINE = '#303A25'

COLOR_CLAMPS_FILL = '#afc6c0'
COLOR_CLAMPS_OUTLINE = '#516a64'
COLOR_CLAMPS_OUTLINE_PUSHED = 'black'
COLOR_HIGHLIGHT = 'yellow'

COLOR_LINES = 'black'
COLOR_NODE_FILL = 'black'
